on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  converter_job:
    runs-on: ubuntu-latest
    name: Test convert v5 image
    steps:
      - uses: actions/checkout@v3
      - name: convert image
        uses: ./
        with:
          source: "docker.io/library/alpine:latest"
          fs-version: "5"
          registry: ${{ env.REGISTRY }}
          repository: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
